FROM node:20-alpine

WORKDIR /app
RUN npm install -g pnpm
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

COPY . .
RUN pnpm install

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "start","--","-p","3000"]