name: Deploy Dockerized Express App to AWS VM

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.AWS_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./2-react-express-todo
        file: ./2-react-express-todo/backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-backend-todo:${{ github.sha }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./2-react-express-todo
        file: ./2-react-express-todo/frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend-todo:${{ github.sha }}

    - name: Deploy to AWS VM
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react-backend-todo:${{ github.sha }}
        sudo docker run -d -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/react-backend-todo:${{ github.sha }}
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend-todo:${{ github.sha }}
        sudo docker run -d -p 4173:4173 ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend-todo:${{ github.sha }}
        EOF
