name: Deploy React Prisma App to AWS VM

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.AWS_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to AWS VM
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          cd /home/${{ secrets.AWS_USER }}/ForDevOps/"6. react-prisma-todo"/backend
          git pull origin main
          npm install
          touch .env
          echo "DATABASE_URL='${{ secrets.DATABASE_URL }}'" > .env
          npx prisma generate
          npx prisma migrate deploy
          npm run build
          pm2 describe react-prisma-backend-app > /dev/null && pm2 restart react-prisma-backend-app || pm2 start "npm start" --name react-prisma-backend-app
          cd /home/${{ secrets.AWS_USER }}/ForDevOps/"6. react-prisma-todo"/frontend
          npm install
          npm run build
          pm2 describe react-prisma-frontend-app > /dev/null && pm2 restart react-prisma-frontend-app || pm2 start "npm run preview -- --host 0.0.0.0" --name react-prisma-frontend-app
        EOF
