name: Deploy Dockerized Express App to AWS VM

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.AWS_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./1-express-todo
        file: ./1-express-todo/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/express-todo:${{ github.sha }}

    - name: Deploy to AWS VM
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'

        echo "Cleaning old containers..."
        sudo docker stop express-todo || true
        sudo docker rm express-todo || true

        echo "Removing old images..."
        sudo docker image prune -af || true

        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/express-todo:${{ github.sha }}
        sudo docker run -d -p 3001:3001 ${{ secrets.DOCKERHUB_USERNAME }}/express-todo:${{ github.sha }}
        EOF
